version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: poc_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: poc_auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    container_name: poc_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: poc_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata: